[versions]
# Plugin versions
pluginYmlPaper = "0.8.0"
runPaper = "3.0.2"
lombok = "9.2.0"
shadow = "9.3.1"
licenser = "2.2.2"

# Dependency versions
lamp = "4.0.0-rc.14"
paper-api = "1.21.11-R0.1-SNAPSHOT"

[libraries]
# Dependencies
lamp-common = { group = "io.github.revxrsal", name = "lamp.common", version.ref = "lamp" }
lamp-bukkit = { group = "io.github.revxrsal", name = "lamp.bukkit", version.ref = "lamp" }
paper-api = { group = "io.papermc.paper", name = "paper-api", version.ref = "paper-api" }

[bundles]
lamp = ["lamp-common", "lamp-bukkit"]

[plugins]
plugin-yml-paper = { id = "de.eldoria.plugin-yml.paper", version.ref = "pluginYmlPaper" }
run-paper = { id = "xyz.jpenilla.run-paper", version.ref = "runPaper" }
lombok = { id = "io.freefair.lombok", version.ref = "lombok" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
licenser = { id = "dev.yumi.gradle.licenser", version.ref = "licenser" }
